name: Deploy site

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ${{ github.event.repository.name }}


    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          docker build -t $IMAGE_NAME:latest .

      - name: Save Docker image to archive
        run: |
          mkdir -p deploy
          docker save $IMAGE_NAME:latest | gzip > ./deploy/$IMAGE_NAME.tar.gz

      - name: Copy image to server image store folder
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "./deploy/${{ env.IMAGE_NAME }}.tar.gz"
          target: "~/deploy/"

      - name: Deploy on server and run service
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker load -i ~/deploy/${{ env.IMAGE_NAME }}.tar.gz
#           rm -rf ~/deploy/* || true
            cd ~/compose-files/production
            docker compose down || true
            docker compose up -d --force-recreate
